#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Go to frontend folder
cd frontend || exit 1

echo "🔹 Running build..."
npm run build || exit 1

echo "✅ All pre-push checks passed. You can push now!"